-- SQL: create admin table for site admin logins
-- Save this file and run it against your MySQL/MariaDB database.

-- Replace `poppik_academy` with your database name if necessary.

CREATE TABLE IF NOT EXISTS `admins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_admin_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Example: DO NOT store plaintext passwords. Use a password hash generated by PHP
-- Example workflow:
-- 1) Generate a bcrypt hash in PHP: $hash = password_hash('YourPasswordHere', PASSWORD_DEFAULT);
-- 2) Use the generated hash in the INSERT below.

-- INSERT EXAMPLE (replace <hash_from_php> with the real hash generated by PHP):
-- INSERT INTO `admins` (`email`, `password`, `name`) VALUES
-- ('admin@example.com', '<hash_from_php>', 'Site Admin');

-- Quick PHP snippet to create an admin (run in a safe environment):
-- <?php
-- // generate hash
-- $hash = password_hash('admin123', PASSWORD_DEFAULT);
-- echo "Generated hash: $hash\n";
-- // then using PDO to insert safely
-- /*
-- $pdo = new PDO('mysql:host=localhost;dbname=poppik_academy;charset=utf8mb4', 'dbuser', 'dbpass');
-- $stmt = $pdo->prepare('INSERT INTO admins (email, password, name) VALUES (?, ?, ?)');
-- $stmt->execute(['admin@example.com', $hash, 'Site Admin']);
-- */
-- ?>

-- Login usage note (PHP): use password_verify($passwordFromForm, $hashFromDb)
